# Generated by Django 4.1 on 2023-05-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=1000)),
                ('episodes', models.IntegerField()),
                ('description', models.TextField()),
                ('genres', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAnimeRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackingApp.anime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackingApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('episode_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('filler', models.BooleanField(default=False)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrackingApp.anime')),
            ],
        ),
    ]
